-- SOHOJ KHATA SUBAPASE DATABASE SCHEMA
-- Paste this script directly into your Supabase SQL Editor to initialize the necessary tables
-- for your digital decentralized ledger marketplace.

-- 1. Create the Users Table (Merchants / Shopkeepers)
CREATE TABLE IF NOT EXISTS public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    phone text NOT NULL,
    "shopName" text NOT NULL,
    "shopType" text NOT NULL,
    "upiId" text NOT NULL,
    pin text NOT NULL,
    "createdAt" bigint NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint
);

-- Enable RLS for Users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create liberal policies or generic access policies since this is a public ledger system
CREATE POLICY "Allow public read users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update users" ON public.users FOR UPDATE USING (true);
CREATE POLICY "Allow public delete users" ON public.users FOR DELETE USING (true);


-- 2. Create the Customers Table (Clients assigned to Merchants)
CREATE TABLE IF NOT EXISTS public.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ownerId" integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name text NOT NULL,
    phone text NOT NULL,
    email text,
    "totalDues" double precision NOT NULL DEFAULT 0.0,
    "lastTransactionAt" bigint NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    "createdAt" bigint NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    "isJoined" boolean NOT NULL DEFAULT false
);

-- Create index on ownerId for faster lookups
CREATE INDEX IF NOT EXISTS idx_customers_owner ON public.customers("ownerId");

-- Enable RLS for Customers
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read customers" ON public.customers FOR SELECT USING (true);
CREATE POLICY "Allow public insert customers" ON public.customers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update customers" ON public.customers FOR UPDATE USING (true);
CREATE POLICY "Allow public delete customers" ON public.customers FOR DELETE USING (true);


-- 3. Create the Transactions Table (Ledger Entries)
CREATE TABLE IF NOT EXISTS public.transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customerId" integer NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    amount double precision NOT NULL,
    type text NOT NULL, -- 'GIVE' or 'GET'
    description text NOT NULL,
    "paymentMethod" text NOT NULL, -- 'CASH', 'UPI', 'OTHER'
    timestamp bigint NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint
);

-- Create index on customerId for faster lookups
CREATE INDEX IF NOT EXISTS idx_transactions_customer ON public.transactions("customerId");

-- Enable RLS for Transactions
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read transactions" ON public.transactions FOR SELECT USING (true);
CREATE POLICY "Allow public insert transactions" ON public.transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update transactions" ON public.transactions FOR UPDATE USING (true);
CREATE POLICY "Allow public delete transactions" ON public.transactions FOR DELETE USING (true);
